### ISSUE TITLE
When is it safe to use the plugin?

### ISSUE THREAD

**Issue by mansxu** [tgardner/cordova-pebble#1]
I am trying to figure out when the plugin is loaded. I tried tying it to the ready event on the document, but calling Pebble gives me an error. When I call the methods after the page is loaded (say, by pushing a button) everything works fine. Is there a particular event that tells me the interface is available and ready to use?

**Comment by tgardner** [comment]
The pebble plugin is available after the [deviceready](https://cordova.apache.org/docs/en/4.0.0/cordova/events/events.deviceready.html) event fires.
