### ISSUE TITLE
iOS app submission ERROR because of PebbleKit Framework

### ISSUE THREAD

**Issue by ragcsalo** [tgardner/cordova-pebble#2]
I got the following error messages from Apple when trying to submit my app (using this Pebble plugin):

ERROR 1: Invalid Binary Architecture - iOS 3.0 introduced support for multiple binary architectures. If your binary is built for multiple architectures, your Info.plist must have a MinimumOSVersion key with a value of at least 3.0. Additionally, if your app is intended to support earlier iPhone and iPod touch models, your app must contain at least an armv6 binary; "thin" armv7-only binaries will not be accepted unless the armv7 required device capability is also present in the Info.plist UIRequiredDeviceCapabilities key or the MinimumOSVersion key has a value of 4.3 or higher.
Specifically, we found the following unsupported architectures in your binary:
x86_64
i386
For more information, see Technical Q&A QA1707 at: http://developer.apple.com/iphone/library/qa/qa2010/qa1707.html.

ERROR 2: Invalid Segment Alignment - The app binary at 'Mental Painter.app/Frameworks/PebbleKit.framework/PebbleKit' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version.

ERROR 3: Invalid Encryption Info - The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.

When I don't use your Pebble plugin, I get no error messages.
(About ERROR #1: I specified the minimum OS version as 8.0, but I still get this error message...)

Can you do something about it? I hope so... :-)

**Comment by ragcsalo** [comment]
I also got this warning message (non-critical):

Non-PIE Binary - The executable 'Payload/Mental Painter.app/Frameworks/PebbleKit.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information, refer to Technical Q&A QA1788 - Building a Position Independent Executable

**Comment by tgardner** [comment]
Hi @ragcsalo ,

Take a look at https://stackoverflow.com/questions/30547283/submit-to-app-store-issues-unsupported-architecture-x86
The PebbleKit.framework is a fat library which includes the simulator and device architectures.

Let me know if it helps.

**Comment by ragcsalo** [comment]
Thanks! :-) 
Unfortunately I can't edit the build script, as I use PhoneGap Build to generate the .ipa file... :-(

Is there another solution, or I have to install Cordova on a Mac (I only have a virtual machine), and build the .ipa with Xcode?

**Comment by ragcsalo** [comment]
I opened an issue in the Adobe forums, hopefully someone can solve this bug...
https://forums.adobe.com/message/10177215

**Comment by ragcsalo** [comment]
In the meantime I've found this info:
Submitting iOS apps with PebbleKit to Apple's App Store
In order for Pebble to work with iPhones, Pebble is part of the Made For iPhone program (a requirement for hardware accessories to interact with iOS apps). Unfortunately this also means that if you build an iOS app with PebbleKit, Pebble will need to whitelist your iOS app before you can upload it to the App Store. If you have completed a Pebble app and would like to learn more about making it available on the App Store, please visit the [whitelisting guide](https://developer.pebble.com/guides/appstore-publishing/whitelisting/)

Because Pebble is now dicontinued, they don't whitelist any new apps..... this means we can't publish new apps with Pebble support for iOS. :-((((((((((((((((((

**Comment by tgardner** [comment]
Hi @ragcsalo,

I've added some build hooks to the dev branch, which should add the necessary steps to strip the simulator architectures during build. Try and installing https://github.com/tgardner/cordova-pebble.git#dev

Let me know if that fixes it and I'll merge it into master.

Cheers,

Trent

**Comment by ragcsalo** [comment]
Dear Trent,
I copied the new/modified files to my fork: https://github.com/ragcsalo/cordova-pebble
I made the build with PhoneGap Build, uploaded the .ipa to iTunes Connect, but I still get the same errors...

Anyway, don't bother too much with this, because what I wrote earlier: Pebble is now dicontinued, they don't whitelist any new apps..... this means I can't publish new apps with Pebble support for iOS even if we don't get any errors. :-( I have to learn how to communicate with the Apple Watch.
