### ISSUE TITLE
App crashes when Bluetooth turned OFF

### ISSUE THREAD

**Issue by ragcsalo** [tgardner/cordova-pebble#5]
If the app is running (or is in the background) and I turn OFF Bluetooth, the app always crashes... Firebase always reports this error:

File: LoadedApk.java

Exception message:
java.lang.RuntimeException: Error receiving broadcast Intent { act=com.getpebble.action.PEBBLE_DISCONNECTED flg=0x10 (has extras) } in net.trentgardner.cordova.pebble.PebblePlugin$2@4a51049 at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$-android_app_LoadedApk$ReceiverDispatcher$Args_52226(LoadedApk.java:1329)

**Comment by ragcsalo** [comment]
This problem still exists...

**Comment by tgardner** [comment]
I'm not sure sorry, I no longer have access to a pebble. Happy to accept a pull request if you figure it out.

**Comment by ragcsalo** [comment]
I have the solution!!! :-) Here is the change:
https://github.com/ragcsalo/cordova-pebble/commit/e68a88037c0cce24c1fa913e66d3ca00753803f9
